### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by s33k3rs** [RTAndrew/rtandrew#23]
What is Laravel Version?

**Comment by s33k3rs** [comment]
I'm sorry, I'm newbie for laravel

**Comment by RTAndrew** [comment]
As of now, the project is using the earliest version of 6.* (not sure what version). However, the dependencies will cause no trouble if you fork it and start it up (make sure you create the database first, and run `php artisan migrate:fresh --seed` )

Have a look at the [composer file](https://github.com/RTAndrew/rtandrew/blob/master/composer.json), under the "require", to see the libraries and its version that the project requires.

**Comment by s33k3rs** [comment]
i can restore main database with "php artisan db:seed"

how about voyager database?

**Comment by RTAndrew** [comment]
Voyager database can be started with dummy data if you wish. Check this [doc](https://github.com/the-control-group/voyager).

And since you are playing with this repo, make sure you do `npm install` so the static files are built.
